// Type surface for the shadow-cljs :esm output (news.core / news.policy /
// news.score). The bundle (news.js) is generated by `amu compile --target wasm32-browser
// worker`; these are hand-written signatures for the exported pure fns.
// Inputs/outputs cross the CLJS↔JS boundary as plain JS objects/strings.

declare module "../js/news.js" {
  export function validatePublishIntel(obj: unknown): { valid: boolean; error?: string };
  export function validateCommitArticle(obj: unknown): { valid: boolean; error?: string };
  export function articleToTxEdn(article: unknown): string;
  export function reconcilePostTxEdn(articleId: string, postUri: string, updatedAt: string): string;
  export function liveAudioSourceToTxEdn(src: unknown): string;
  export function scheduleStateTxEdn(state: unknown): string;
  export function articleToPostText(article: unknown): string;
  export function writerDidForSource(sourceName: string): string;
  export function qListArticles(sourceId: string | null): string;
  export function qByArticleId(articleId: string): string;
  export function qByRkey(rkey: string): string;
  export function qListSources(kind: string | null): string;
  export function qListLiveAudioSources(status: string | null): string;
  export function qStats(): string;
  export function shapeRows(rowsEdn: unknown): any[];
  export function decodeEntityEdn(s: string): Record<string, unknown> | null;
  export function liveAudioPolicyGate(obj: unknown): {
    rightsPolicy: string; publishAllowed: boolean; retainAllowed: boolean; blocked: boolean; reason: string;
  };
  export function scoreIntel(obj: unknown): {
    socialArbitrageScore: number; priority: number; credibility: number;
    bridgeScores: Record<string, number>;
  };
}
